name: build-msys2-clang64-nurbs
on:
  push:
  pull_request:
jobs:
  msys2-clang64-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Install MSYS2 and clang64 packages
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: clang64
          update: true
          install: >-
            make
            mingw-w64-clang-x86_64-clang
            mingw-w64-clang-x86_64-clang++
            mingw-w64-clang-x86_64-make
            mingw-w64-clang-x86_64-cmake
            mingw-w64-clang-x86_64-pkg-config
            git
            mingw-w64-clang-x86_64-mesa
            mingw-w64-clang-x86_64-freeglut
            mingw-w64-clang-x86_64-glew
    
      - name: Build
        run: |
          cd raytrace
          make 
          
      - name: Package artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: clang64-msys2-build
          path: .
          if-no-files-found: warn
