name: build-cygwin-nurbs

on:
  push:
  pull_request:

jobs:
  cygwin-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Cygwin and core packages
      - name: Install Cygwin + deps
        uses: cygwin/cygwin-install-action@master
        with:
          # Base toolchain + cmake + pkg-config + git
          packages: >-
            gcc-g++
            make
            cmake
            pkg-config
            git
            # OpenGL + GLU + GLUT headers/libs for Cygwin
            libGL-devel
            libGLU-devel
            libglut-devel

    
     


      - name: Build
        shell: bash {0}
        run: 
          cd ${{ github.workspace }}
          cd raytrace
          make -j"$(nproc)"

      - name: Package artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.backend }}-cygwin-build
          path: .
          if-no-files-found: warn
