name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      

      

      

        
  
        

        

        
   
      
    # C/C++ projects with Makefile
    - name: Build C/C++ project (Makefile)
      run: |
       cd raytrace
       make Makefile.win32
      
  
      
    - name: Test .NET project
      if: hashFiles('*.csproj') != '' || hashFiles('*.sln') != ''
      run: dotnet test
